<?php

/**
 * Created by PhpStorm.
 * User: thuanpt
 * Date: 15/07/2017
 * Time: 12:03
 */
abstract class test1
{
    abstract function cho();
    function meo(){
        return 'day la meo';
    }
    final function khi(){
        return '<br>'.'day la khi';
    }
}
class pet extends test1{
    function cho()
    {
        return '<br>'."good pet".'<br>';// TODO: Implement cho() method.
    }
    function meo()
    {
        return parent::meo(); // TODO: Change the autogenerated stub
    }
}
$animal = new pet;
echo $animal->cho();
echo $animal->meo();
echo $animal->khi();